### ISSUE TITLE
Possible lost of CLO

### ISSUE THREAD

**Issue by k06a** [EthereumCommonwealth/Cold-staking#7]
Remove debug method to avoid CLO coin losts:
https://github.com/EthereumCommonwealth/Cold-staking/blob/863846e510299b8cb07bab38c0b60d1bd78e9947/ColdStaking.sol#L162

Auditing smart contracts in live stream: https://www.youtube.com/watch?v=efZY3_COaiE

Your CryptoManiacs :)

**Comment by k06a** [comment]
You need to create separate method with `only_treasurer` modifier to refill balance by treasurer:
```
function deposit() public payable only_treasurer {
    emit TreasurerDeposited(msg.sender, msg.value);
}
```

**Comment by Dexaran** [comment]
Not only Treasurer must have access to this function. We assume that some users may want to donate too. 

Most of the projects have "official donation wallet". We have Treasury (if someone wants to donate for CLO dev team) and Staking Contract (if someone wants to donate for CLO community).

**Comment by k06a** [comment]
Treasurer itself could be used for donations, hope no one will call this method for a mistake.
