### ISSUE TITLE
Duplicate condition

### ISSUE THREAD

**Issue by k06a** [EthereumCommonwealth/Cold-staking#8]
Remove this condition:
https://github.com/EthereumCommonwealth/Cold-staking/blob/863846e510299b8cb07bab38c0b60d1bd78e9947/ColdStaking.sol#L175

Because of exactly the same condition a few lines ago:
https://github.com/EthereumCommonwealth/Cold-staking/blob/863846e510299b8cb07bab38c0b60d1bd78e9947/ColdStaking.sol#L171

Auditing smart contracts in live stream: https://www.youtube.com/watch?v=efZY3_COaiE

Your CryptoManiacs :)

**Comment by Dexaran** [comment]
Confirmed.

**Comment by Dexaran** [comment]
Paid https://explorer2.callisto.network/tx/0x846d54174d22cba91c42f0e401b6d54f4b79c568cb887985108cb12a4908a078

**Comment by k06a** [comment]
@Dexaran thanks!
